### ISSUE TITLE
CRUD Features for User, Recycling Submission, Merchant, Reward, Redemption

### ISSUE THREAD

**Issue by keithxun** [miloaisdino/greenapp#4]
**User**

user_id (Primary Key)
username
password (hashed)
email
full_name
profile_picture_url
points_balance
date_joined

**Recycling Submission**

submission_id (Primary Key)
user_id (Foreign Key referencing User)
image_url (URL of the uploaded image)
submission_date
description
points_awarded

**Merchant**

merchant_id (Primary Key)
name
description
logo_url
contact_email
contact_phone
address

**Reward**

reward_id (Primary Key)
merchant_id (Foreign Key referencing Merchant)
name
description
image_url
points_cost (Points required to redeem the reward)
available_quantity

**Redemption**

redemption_id (Primary Key)
user_id (Foreign Key referencing User)
reward_id (Foreign Key referencing Reward)
redemption_date
status (e.g., "Pending", "Completed", "Cancelled")
quantity (Number of items redeemed)

**Comment by maximustan2** [comment]
schema lgtm

**Comment by maximustan2** [comment]
https://github.com/miloaisdino/greenapp/issues/6 for recycling submission endpoint

**Comment by maximustan2** [comment]
#6 resolved

**Comment by maximustan2** [comment]
#9 for merchant, reward, redemption endpoints

**Comment by maximustan2** [comment]
tag @keithxun for pr approval
